# Available embedding model options that run locally:
# - all-MiniLM-L6-v2       (small + fast)
# - all-mpnet-base-v2      (more accurate)
# - paraphrase-MiniLM-L12-v2
# - multi-qa-MiniLM-L6-cos-v1  (QA-focused)
# - all-distilroberta-v1
embedding:
  provider: local
  model_name: all-MiniLM-L6-v2 

llm:
  provider: ollama
  ollama:
    model: phi4
    url: http://localhost:11434/api/generate
  openai:
    model: o4-mini
    api_key_env: OPENAI_API_KEY

vector_store:
  vector_store_to_use: faiss
  faiss:
    folder_name: stored_vectors
    index_file: faiss_index.index
    texts_file: faiss_texts.pkl
  pinecone:
    api_key_env: PINECONE_API_KEY  # name of the environment variable
    index_name: my-rag-app-v2-test

documents:
  source_dir: "data/documents"  # <- Path to the folder with .txt, .pdf, etc.